
package VIEW;

import DAO.ControleBairroDAO;
import DTO.ControleBairroDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BairroView extends javax.swing.JFrame {

    /**
     * Creates new form BairroView
     */
    public BairroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelImagem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelControle = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        Abas = new javax.swing.JTabbedPane();
        AbaConsulta = new javax.swing.JPanel();
        AbaCadastro = new javax.swing.JPanel();
        labelCadastro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        botaoCadastro = new javax.swing.JButton();
        AbaAtual = new javax.swing.JPanel();
        AbaExclusao = new javax.swing.JPanel();
        labelExclusao = new javax.swing.JLabel();
        cmbExcluir = new javax.swing.JComboBox<>();
        botaoExcluir = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        AgenciasMenu = new javax.swing.JMenu();
        BairrosMenu = new javax.swing.JMenu();
        ClientesMenu = new javax.swing.JMenu();
        ContasMenu = new javax.swing.JMenu();
        TransacMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/banner_op.png"))); // NOI18N

        javax.swing.GroupLayout PainelImagemLayout = new javax.swing.GroupLayout(PainelImagem);
        PainelImagem.setLayout(PainelImagemLayout);
        PainelImagemLayout.setHorizontalGroup(
            PainelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelImagemLayout.setVerticalGroup(
            PainelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setName(""); // NOI18N
        label2.setText("Controle de Bairros");

        Abas.setName("Consulta"); // NOI18N

        javax.swing.GroupLayout AbaConsultaLayout = new javax.swing.GroupLayout(AbaConsulta);
        AbaConsulta.setLayout(AbaConsultaLayout);
        AbaConsultaLayout.setHorizontalGroup(
            AbaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        AbaConsultaLayout.setVerticalGroup(
            AbaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        Abas.addTab("Consulta", AbaConsulta);

        labelCadastro.setText("Nome do Bairro");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        botaoCadastro.setText("Cadastrar");
        botaoCadastro.setName(""); // NOI18N
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaCadastroLayout = new javax.swing.GroupLayout(AbaCadastro);
        AbaCadastro.setLayout(AbaCadastroLayout);
        AbaCadastroLayout.setHorizontalGroup(
            AbaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoCadastro)
                        .addGroup(AbaCadastroLayout.createSequentialGroup()
                            .addComponent(labelCadastro)
                            .addGap(70, 70, 70)))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        AbaCadastroLayout.setVerticalGroup(
            AbaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCadastroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCadastro)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        Abas.addTab("Cadastro", AbaCadastro);

        javax.swing.GroupLayout AbaAtualLayout = new javax.swing.GroupLayout(AbaAtual);
        AbaAtual.setLayout(AbaAtualLayout);
        AbaAtualLayout.setHorizontalGroup(
            AbaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        AbaAtualLayout.setVerticalGroup(
            AbaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        Abas.addTab("Atualização", AbaAtual);

        labelExclusao.setText("Nome do Bairro");

        cmbExcluir.setName(""); // NOI18N
        cmbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbExcluirActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaExclusaoLayout = new javax.swing.GroupLayout(AbaExclusao);
        AbaExclusao.setLayout(AbaExclusaoLayout);
        AbaExclusaoLayout.setHorizontalGroup(
            AbaExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaExclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoExcluir)
                        .addGroup(AbaExclusaoLayout.createSequentialGroup()
                            .addComponent(labelExclusao)
                            .addGap(73, 73, 73)))
                    .addComponent(cmbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        AbaExclusaoLayout.setVerticalGroup(
            AbaExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaExclusaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelExclusao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        Abas.addTab("Exclusão", AbaExclusao);

        javax.swing.GroupLayout PainelControleLayout = new javax.swing.GroupLayout(PainelControle);
        PainelControle.setLayout(PainelControleLayout);
        PainelControleLayout.setHorizontalGroup(
            PainelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Abas))
        );
        PainelControleLayout.setVerticalGroup(
            PainelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelControleLayout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Abas, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AgenciasMenu.setText("Agências");
        Menu.add(AgenciasMenu);

        BairrosMenu.setText("Bairros");
        Menu.add(BairrosMenu);

        ClientesMenu.setText("Clientes");
        Menu.add(ClientesMenu);

        ContasMenu.setText("Contas");
        Menu.add(ContasMenu);

        TransacMenu.setText("Transações");
        Menu.add(TransacMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
       ControleBairroDTO objbairrodto = new ControleBairroDTO();
       ControleBairroDAO objbairrodao = new ControleBairroDAO();
       String nomebairro = txtNome.getText();
       
       objbairrodto.setNome(nomebairro);
       objbairrodao.cadastrarBairro(objbairrodto);
       
       txtNome.setText("");
    //    listarBairro();
        
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void cmbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbExcluirActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
       ControleBairroDTO objbairrodto = new ControleBairroDTO();
       ControleBairroDAO objbairrodao = new ControleBairroDAO();
       String nome = (String) cmbExcluir.getSelectedItem();
       int id = objbairrodao.pesquisarBairroId(nome);
       
       objbairrodto.setId(id);
       
       objbairrodao.excluirBairro(objbairrodto);
       listarBairro();
       
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BairroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BairroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BairroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BairroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BairroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaAtual;
    private javax.swing.JPanel AbaCadastro;
    private javax.swing.JPanel AbaConsulta;
    private javax.swing.JPanel AbaExclusao;
    private javax.swing.JTabbedPane Abas;
    private javax.swing.JMenu AgenciasMenu;
    private javax.swing.JMenu BairrosMenu;
    private javax.swing.JMenu ClientesMenu;
    private javax.swing.JMenu ContasMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel PainelControle;
    private javax.swing.JPanel PainelImagem;
    private javax.swing.JMenu TransacMenu;
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JComboBox<String> cmbExcluir;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label2;
    private javax.swing.JLabel labelCadastro;
    private javax.swing.JLabel labelExclusao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

 private List listarBairro() {
        ControleBairroDAO objbairrodao = new ControleBairroDAO();
        
        List<ControleBairroDTO> lista = objbairrodao.pesquisarBairro();
        
        try {
 //           DefaultTableModel model = (DefaultTableModel) tabbairro.getModel();
 //           model.setRowCount(0);

//            cmbupbairro.removeAllItems();
              cmbExcluir.removeAllItems();

            for (ControleBairroDTO bairro : lista) {
                model.addRow(new Object[]{
//                    bairro.getId(),
//                    bairro.getNome()
//                });

//              lblupidbairro.setText(bairro.getId());
  //              cmbupbairro.addItem(bairro.getNome());
                cmbExcluir.addItem(bairro.getNome());
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "listar Valores VIEW: " + e);
        }
        return lista;
    }
}
